name: BurgerStrategist
on: 
  workflow_dispatch:
  
  # schedule:
  # - cron: "0 0,4,8,12,16,20 * * *"
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Run Strategy
      run: echo ${{ secrets.CONFIG_N3T5 }} | dotnet run --project BurgerStrategist
      env:
        WIF: ${{ secrets.TEEWIF }}
        RPC: http://seed3t5.neo.org:20332
